import Java from "frida-java-bridge";

(globalThis as any).Java = Java;

function evalLegacy(source: string, label: string): void {
  (0, eval)(`${source}\n//# sourceURL=${label}`);
}

evalLegacy("\n(function () {\n    function toText(args) {\n        try {\n            return Array.prototype.slice.call(args).map(function (item) {\n                if (typeof item === \"string\") {\n                    return item;\n                }\n                try {\n                    return JSON.stringify(item);\n                } catch (_) {\n                    return String(item);\n                }\n            }).join(\" \");\n        } catch (_) {\n            return \"[console bridge serialize failed]\";\n        }\n    }\n\n    function bridge(level, originalFn) {\n        return function () {\n            var text = toText(arguments);\n            try {\n                send({\n                    type: \"console\",\n                    level: level,\n                    message: text\n                });\n            } catch (_) {\n            }\n            if (typeof originalFn === \"function\") {\n                try {\n                    originalFn.apply(console, arguments);\n                } catch (_) {\n                }\n            }\n        };\n    }\n\n    if (typeof console !== \"undefined\") {\n        console.log = bridge(\"log\", console.log);\n        console.warn = bridge(\"warn\", console.warn);\n        console.error = bridge(\"error\", console.error);\n    }\n})();\n", 'console-bridge.js');
evalLegacy("Java.perform(function () {\n    var VerifyCodeLoginParam = Java.use('com.immomo.android.mvvm.phonelogin.domain.b.c');\n\n    var init = VerifyCodeLoginParam.$init.overload('java.lang.String','java.lang.String','java.lang.String','java.lang.String','java.lang.String','boolean','java.lang.String','java.lang.String','java.lang.String','java.util.Map');\n\n    init.implementation = function (completePhoneNumber,smsCode,smsToken,areaCode,phoneNumber,isAddingMultiAccount,previousUserId,selectToken,selectMomoid,extraParam) {\n        console.log('[VerifyCodeLoginParam.$init]');\n        console.log('completePhoneNumber=' + completePhoneNumber);\n        console.log('smsCode=' + smsCode);\n        console.log('smsToken=' + smsToken);\n        console.log('areaCode=' + areaCode);\n        console.log('phoneNumber=' + phoneNumber);\n        console.log('isAddingMultiAccount=' + isAddingMultiAccount);\n        console.log('previousUserId=' + previousUserId);\n        console.log('selectToken=' + selectToken);\n        console.log('selectMomoid=' + selectMomoid);\n        console.log('extraParam=' + extraParam);\n\n        return init.call(this,completePhoneNumber,smsCode,smsToken, areaCode,phoneNumber,isAddingMultiAccount, previousUserId,selectToken,selectMomoid,extraParam);\n    };\n});\n", "hook.js");
evalLegacy("rpc.exports = {\n    cleanup: function () {\n        // \u6e05\u7406\u6240\u6709\u62e6\u622a\u5668\n        Interceptor.detachAll();\n        // \u5982\u679c\u4f60\u8bbe\u7f6e\u4e86\u5b9a\u65f6\u5668\u6216 Stalker\uff0c\u4e5f\u53ef\u4ee5\u6e05\u7406\n        Stalker.unfollow();\n        // clearInterval(...);\n    }\n};", '_hook_js_warp.js');
