import Java from "frida-java-bridge";

(globalThis as any).Java = Java;

function evalLegacy(source: string, label: string): void {
  (0, eval)(`${source}\n//# sourceURL=${label}`);
}

evalLegacy("\n(function () {\n    function toText(args) {\n        try {\n            return Array.prototype.slice.call(args).map(function (item) {\n                if (typeof item === \"string\") {\n                    return item;\n                }\n                try {\n                    return JSON.stringify(item);\n                } catch (_) {\n                    return String(item);\n                }\n            }).join(\" \");\n        } catch (_) {\n            return \"[console bridge serialize failed]\";\n        }\n    }\n\n    function bridge(level, originalFn) {\n        return function () {\n            var text = toText(arguments);\n            try {\n                send({\n                    type: \"console\",\n                    level: level,\n                    message: text\n                });\n            } catch (_) {\n            }\n            if (typeof originalFn === \"function\") {\n                try {\n                    originalFn.apply(console, arguments);\n                } catch (_) {\n                }\n            }\n        };\n    }\n\n    if (typeof console !== \"undefined\") {\n        console.log = bridge(\"log\", console.log);\n        console.warn = bridge(\"warn\", console.warn);\n        console.error = bridge(\"error\", console.error);\n    }\n})();\n", 'console-bridge.js');
evalLegacy("Java.perform(function () {\n    function hookLoginSessionD() {\n        try {\n            var Cls = Java.use(\"com.max.xiaoheihe.module.account.LoginSession\");\n            var overload = Cls.d.overload();\n\n            overload.implementation = function () {\n                console.log(\"[*] HIT com.max.xiaoheihe.module.account.LoginSession.d()\");\n                return overload.call(this);\n            };\n\n            console.log(\"[+] Hooked com.max.xiaoheihe.module.account.LoginSession.d()\");\n        } catch (e) {\n            console.log(\"[-] Failed to hook com.max.xiaoheihe.module.account.LoginSession.d(): \" + e);\n        }\n    }\n\n    function hookRegisterOrLoginActivityV2L3() {\n        try {\n            var Cls = Java.use(\"com.max.xiaoheihe.module.account.RegisterOrLoginActivityV2\");\n            var overload = Cls.l3.overload();\n\n            overload.implementation = function () {\n                console.log(\"[*] HIT com.max.xiaoheihe.module.account.RegisterOrLoginActivityV2.l3()\");\n                return overload.call(this);\n            };\n\n            console.log(\"[+] Hooked com.max.xiaoheihe.module.account.RegisterOrLoginActivityV2.l3()\");\n        } catch (e) {\n            console.log(\"[-] Failed to hook com.max.xiaoheihe.module.account.RegisterOrLoginActivityV2.l3(): \" + e);\n        }\n    }\n\n    hookLoginSessionD();\n    hookRegisterOrLoginActivityV2L3();\n});\n", "hook.js");
evalLegacy("rpc.exports = {\n    cleanup: function () {\n        // \u6e05\u7406\u6240\u6709\u62e6\u622a\u5668\n        Interceptor.detachAll();\n        // \u5982\u679c\u4f60\u8bbe\u7f6e\u4e86\u5b9a\u65f6\u5668\u6216 Stalker\uff0c\u4e5f\u53ef\u4ee5\u6e05\u7406\n        Stalker.unfollow();\n        // clearInterval(...);\n    }\n};", '_hook_js_warp.js');
